export const lang = {
    id: {
        appName: 'Catatanku',
        changeLanguage: 'Ganti Bahasa',
        changeColorScheme: 'Ganti Tema',
        login: 'Masuk',
        email: 'Email',
        password: 'Kata Sandi',
        signUp: 'Daftar',
        alreadyHaveAccount: 'Sudah punya akun?',
        dontHaveAccount: 'Belum punya akun?',
        logout: 'Keluar',
        name: 'Nama',
        confirmPassword: 'Konfirmasi Kata Sandi',
        confirmPasswordError: 'Kata sandi dan konfirmasi kata sandi tidak cocok',
        activeNotes: 'Catatan Aktif',
        archivedNotes: 'Terarsip',
        addNote: 'Tambah Catatan',
        title: 'Judul',
        content: 'Isi Catatan',
        add: 'Simpan',
        reset: 'Reset',
        delete: 'Hapus',
        emptyNotes: 'Tidak ada catatan',
        moveToActive: 'Aktifkan',
        moveToArchived: 'Arsipkan',
        pageNotFound: 'Halaman Tidak Ditemukan',
        noteNotFound: 'Catatan Tidak Ditemukan',
    },
    en: {
        appName: 'My Notes',
        changeLanguage: 'Change Language',
        changeColorScheme: 'Change Color Scheme',
        login: 'Login',
        email: 'Email',
        password: 'Password',
        signUp: 'Sign up',
        alreadyHaveAccount: 'Already have an account?',
        dontHaveAccount: "Don't have an account?",
        logout: 'Logout',
        name: 'Name',
        confirmPassword: 'Confirm Password',
        confirmPasswordError: 'Password and confirm password must be the same',
        activeNotes: 'Active Notes',
        archivedNotes: 'Archived',
        addNote: 'Add Note',
        title: 'Title',
        content: 'Content',
        add: 'Add',
        reset: 'Reset',
        delete: 'Delete',
        emptyNotes: 'No notes',
        moveToActive: 'Unarchive',
        moveToArchived: 'Archive',
        pageNotFound: 'Page Not Found',
        noteNotFound: 'Note Not Found',
    },
};
